//
// Created by Alex on 8/13/2023.
//

#ifndef RUEIEGAME_ERRORS_H
#define RUEIEGAME_ERRORS_H

#define ERROR_ENGINE_ERROR       0x101
#define ERROR_TEXTURE_NOT_LOADED 0xA00
#define ERROR_TEXTURE_ALREADY_DECLARED 0xA01

#endif //RUEIEGAME_ERRORS_H
